### ISSUE TITLE
Fix bug that cause broken string during parseKVP if value contain white space.

### ISSUE THREAD

**Issue by isnot** [RomanBurunkov/tm-node-mpd#3]
> Fix broken string during parse song if contain white space.

in PR #1 I wrote that.

However, the Song class's test case did not reproduce the problem.
Because of bypass parseKVP.

I have wrote a new test case focused on parseKVP, and fix it.

diff for [src/protocol.js and test case](https://github.com/isnot/tm-node-mpd/commit/7b5c39717106de1046465f4c967eaab123835fdf)

**Comment by RomanBurunkov** [comment]
Hi @isnot 

That's looks good for me.
Can you create a PR for that?

**Comment by RomanBurunkov** [comment]
Fixed in 0.3.2
